USE [master]
GO
/****** Object:  Database [Social]    Script Date: 02/05/2014 22:09:19 ******/
CREATE DATABASE [Social]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Social', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Social.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Social_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Social_log.ldf' , SIZE = 1040KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Social] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Social].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Social] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Social] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Social] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Social] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Social] SET ARITHABORT OFF 
GO
ALTER DATABASE [Social] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Social] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Social] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Social] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Social] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Social] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Social] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Social] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Social] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Social] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Social] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Social] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Social] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Social] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Social] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Social] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Social] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Social] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Social] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Social] SET  MULTI_USER 
GO
ALTER DATABASE [Social] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Social] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Social] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Social] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [Social]
GO
ALTER DATABASE [Social] SET  READ_WRITE 
GO
USE [Social]
GO